# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'vs2017-win2016'
trigger:
  branches:
    include:
    - master
    - azure-pipelines.yml
  paths:
    include:
    - src/*
    - tests/*
    - samples/*
    exclude:
    - docs/*

variables:
  buildConfiguration: 'Release'
  restoreBuildProjects: '**/*.csproj'
  testProjects: '**/tests/*.Tests/*.csproj'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@3
  displayName: GitVersion
  inputs:
    updateAssemblyInfo: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: $(restoreBuildProjects)

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: $(restoreBuildProjects)
    arguments: '--configuration $(buildConfiguration) /p:Version=$(Build.BuildNumber)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: $(testProjects)
    arguments: '--configuration $(buildConfiguration) --filter Category!=IntegrationTest --no-build'

# Release: when triggered by a version tag (v*) we make a release
- task: DotNetCoreCLI@2
  displayName: NuGet Pack Opw.HttpExceptions
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v*'))
  inputs:
    command: pack
    packagesToPack: '**/Opw.HttpExceptions.csproj'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: NuGet Pack Opw.HttpExceptions.AspNetCore
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v*'))
  inputs:
    command: pack
    packagesToPack: '**/Opw.HttpExceptions.AspNetCore.csproj'
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  displayName: NuGet Push
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v*'))
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: NuGet
    versioningScheme: byBuildNumber

- task: GithubRelease@0
  displayName: Create GitHub Release
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v*'))
  inputs:
   gitHubConnection: GitHub
   repositoryName: $(Build.Repository.Name)
   action: create
   target: $(Build.SourceVersion)
   tagSource: manual
   tag: 'v$(Build.BuildNumber)'
   releaseNotesSource: file
   releaseNotesFile: CHANGELOG.md

# Finalize
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: always()
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
